### ISSUE TITLE
Bug Report: receiving 3 "manage subscriptions" e-mails

### ISSUE THREAD

**Issue by wcruz-br** [stcr/subscribe-to-comments-reloaded#148]
When users provide their e-mail to receive link to the manage subscriptions page, they receive three times the same e-mail:

![image](https://cloud.githubusercontent.com/assets/14890295/10165633/a72f1eb8-6696-11e5-9703-767335b633e5.png)

**Comment by Reedyseth** [comment]
Am update will be release soon, you can test it to see if this fix this bug, since this new update will fix many things on the plugin.

**BETA Repository:** https://github.com/stcr/subscribe-to-comments-reloaded/tree/pre_release
**BETA ZIP file:** https://github.com/stcr/subscribe-to-comments-reloaded/archive/pre_release.zip
