### ISSUE TITLE
Hundreds of 404 error pages on webmaster tools

### ISSUE THREAD

**Issue by juniorBR** [stcr/subscribe-to-comments-reloaded#186]
Hi,

There are hundreds of 404 error pages in Webmaster Tools like this "comment-subscriptions/?srp=1933&sra=s"

My permalink structure is /%postname%/

On Yoast SEO plugin I've checked "Strip the category base (usually /category/) from the category URL.". 

This option is unchecked "Remove the ?replytocom variables."

And finally, I am using a real management page with the following value "/gerenciar-inscricoes/"

Can you help?

Thanks

**Comment by Polipo2** [comment]
Hello, I deactivated StCr plugin because I moved to Disqus, after that I have too many 404 errors on GWT.

For example:
	
comment-subscriptions?srp=49139&srk=f69acae3919548a804e12af6e661f69b&sra=s
comment-subscriptions?srp=50048&srk=f69acae3919548a804e12af6e661f69b&sra=s
comment-subscriptions?srp=40160&srk=f69acae3919548a804e12af6e661f69b&sra=s

Can you help me?

**Comment by raamdev** [comment]
@Polipo2 @clopez You should use Google Webmaster Tools to block access to `?srp=`:
https://support.google.com/webmasters/topic/4598466?rd=1

For example, you can add the following to your `robots.txt` file to block the Google Web Crawler from indexing specific pages:

```
User-agent: *
Disallow: /comment-subscriptions*?srp=*
```
