### ISSUE TITLE
After Update 90% of translation lost.

### ISSUE THREAD

**Issue by micha1848** [stcr/subscribe-to-comments-reloaded#252]
After the last Update about 90% of my german Translation are lost. Thre overwrite by the english defaults...

_Version 160831 of the Plugin and WP = 4.6._

**Comment by Reedyseth** [comment]
Hi @micha1848 ,

I apologize for that, did you make changes in the translation files or it just stopped working ?

**Comment by micha1848** [comment]
Translation Files?
Ok, the Plugin it self is german that works.
But the individual Messages are english after Update. At Commentform the complete Messages are overwritten with english.
At the "administration page" the title are german, but all the Messages are the english Orignals.
And on the Notification Page all my German Translation are still there...
No Idea whats Happend :-)

**Comment by Reedyseth** [comment]
> But the individual Messages are english after Update. At Commentform the complete Messages are overwritten with english.

This is pretty weird because the update does not mess with your messages.

On the new update there is a hidden page, I say hidden because is not visible in the options tabs.

If you go to the left menu of StCR you will see an option named StCR System.

![image](https://cloud.githubusercontent.com/assets/1228711/18172777/1b965d7e-7024-11e6-80cf-22c8881737e9.png)


Would you mind sending me the data to my email? It only has information of the plugin settings, not critical information of your site.

use reedyseth [at| gmail {dot] com

**Comment by Reedyseth** [comment]
@micha1848 I released a new version so please update !
