### ISSUE TITLE
Bug Report: People do not receive the email when subscribed to a post

### ISSUE THREAD

**Issue by nfkb** [stcr/subscribe-to-comments-reloaded#301]
Hello,

I’m sorry for my noob question. The issue is that people do not receive their notification email 🙁
(Me neither when testing with an another email)

I run WP 4.6.1, StCR 160915

The plugin is installed, I can browse through the various subscriptions and so on. The comment subscription page is ok.

I’ve tried to Deactivate/Reactivate without success.

My blog is here http://www.nfkb0.com

Where did I do something bad ?

Thanks +++

**Comment by nfkb** [comment]
Sorry but is there any support for this plugin ??? I've written several messages without any answer !

**Comment by Reedyseth** [comment]
Hi @nfkb,

I apologize for not replying to your messages before, the plugin is out of
budget and I was out of time to keep the development, but I will return to
the development the next week. Also I will take a look into your issue.

Regards.!!
On Dec 15, 2016 11:01 PM, "nfkb" <notifications@github.com> wrote:

Sorry but is there any support for this plugin ??? I've written several
messages without any answer !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stcr/subscribe-to-comments-reloaded/issues/301#issuecomment-267523611>,
or mute the thread

**Comment by Merllin** [comment]
Check your error_log and psot the error here. Id is simillar to this one https://github.com/stcr/subscribe-to-comments-reloaded/issues/303
you have a conflict in your database.

**Comment by Reedyseth** [comment]
@nfkb Are you still having this issue? Please if the error persist reopen the issue and I will be glad to help. Regards.!!
