### ISSUE TITLE
Bug Report: illegal mix of collations

### ISSUE THREAD

**Issue by SanderMe** [stcr/subscribe-to-comments-reloaded#303]
StCR shows the following error message. What do I need to do to solve this? 

WordPress databasefout: [Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_unicode_520_ci,IMPLICIT) for operation '=']
SELECT meta_id, REPLACE(meta_key, '_stcr@_', '') AS email, post_id, SUBSTRING(meta_value, 1, 19) AS dt, SUBSTRING(meta_value, 21) AS status, srs.subscriber_unique_id AS email_key FROM wprn_postmeta INNER JOIN wprn_subscribe_reloaded_subscribers srs ON ( REPLACE(meta_key, '_stcr@_', '') = srs.subscriber_email ) WHERE meta_key LIKE '\_stcr@\_%' AND SUBSTRING(meta_key, 8) LIKE '%@%' ORDER BY dt DESC LIMIT 0,25

WordPress databasefout: [Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_unicode_520_ci,IMPLICIT) for operation '=']
SELECT meta_id, REPLACE(meta_key, '_stcr@_', '') AS email, post_id, SUBSTRING(meta_value, 1, 19) AS dt, SUBSTRING(meta_value, 21) AS status, srs.subscriber_unique_id AS email_key FROM wprn_postmeta INNER JOIN wprn_subscribe_reloaded_subscribers srs ON ( REPLACE(meta_key, '_stcr@_', '') = srs.subscriber_email ) WHERE meta_key LIKE '\_stcr@\_%' AND SUBSTRING(meta_key, 8) LIKE '%@%' ORDER BY dt ASC LIMIT 0,18446744073709551610

**Comment by Merllin** [comment]
You should run a SQL query to change the collation for table wprn_subscribe_reloaded_subscribers.
`ALTER TABLE wprn_subscribe_reloaded_subscribers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

**Comment by Reedyseth** [comment]
@Merllin Thank you for your suggestion. That did the trick. I have noticed that this error raises when users are importing/exporting the database. The thing is that StCR takes the database collate and uses to create the `wp_susbscribe_reloaded_subscribers` table so if the collates clashes then this issue is the result. I have change the default collate of the table new installations, as for the current users the have to execute the query as @Merllin Suggested.
