### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Ysery** [stcr/subscribe-to-comments-reloaded#345]
Hello
As on the management page make time in the format **day** - **month** - **year** hours : minutes : seconds? 

Sorry for my English

**Comment by Reedyseth** [comment]
Hello Ysery, actually somehow better. I will add an option to allow any
formatting on the plugin options.

I will add this as an enhancement.

Thanks for the suggestion !


On May 5, 2017 6:28 PM, "Ysery" <notifications@github.com> wrote:

As on the management page make time in the format day - month - year hours
: minutes : seconds?

Sorry for my English

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stcr/subscribe-to-comments-reloaded/issues/345>, or mute
the thread

**Comment by Ysery** [comment]
Thank you. I will wait

**Comment by Reedyseth** [comment]
Hello @Ysery , this option is now available on the latest version (180225). You will use the PHP date format method:

![image](https://user-images.githubusercontent.com/1228711/36680716-cd91361a-1ad3-11e8-8443-0b86ca931455.png)

------

![image](https://user-images.githubusercontent.com/1228711/36680726-d82584dc-1ad3-11e8-8d0e-f98064aee18f.png)

**Comment by Ysery** [comment]
Many thanks
