### ISSUE TITLE
Bug Report: Not working on two different blogs/themes

### ISSUE THREAD

**Issue by sbradk** [stcr/subscribe-to-comments-reloaded#359]
I've installed this to two different blogs (different themes) and it doesn't work on either. I'm running the latest version of WordPress.

The drop-down list shows and it sends an email to confirm subscription. BUT, the user never shows in the management page; the subscribed column always shows no; when the user goes to manage subscriptions it says to check some items - but no items show on the management page for them.

What might be wrong? Does this not work with the latest version of WP?

Thanks,
Brad

**Comment by Patric77** [comment]
Hi,
I have the exact same problems.

They DO NOT happen on a WP 4.8.1 local fresh install.

But it happens on my WP online site, updated to WP 4.8.1. Even with the default theme activated and every other plugins deleted, it happens.
Please note that it concerns my developpement site, located in a /dev subfolder. I did not try on my original site, but I don't think this could make a difference.
I can provide access to my website to the developper if he wants to make some checks.

The developpement of this module seems to be paused since June. I hope it will restart soon!

Thanks
Patric

**Comment by Patric77** [comment]
A post that helped me a lot to solve this problem:
https://wordpress.org/support/topic/manage-subscriptions-list-empty/#post-9667834

**Comment by Reedyseth** [comment]
Guys, the latest version of the plugin takes care of a database issue, it should be working for you. Please let me know if you still have issues.

Regards.!!
