### ISSUE TITLE
No sunscribe option and broken manage link

### ISSUE THREAD

**Issue by MarkMcPartland** [stcr/subscribe-to-comments-reloaded#381]
Hi guys.
Just activated plugin but the comments form does not show a subscribe checkbox at all.
It does add a 'manage the subscriptions to this Post link but that then goes to a page not found.

My blog is www.longitudinalshift.com

**Comment by Reedyseth** [comment]
Hello @MarkMcPartland , I saw your website. There is something wrong with the link generation. I will check it out and let you know.

Best Regards.!!

**Comment by KLingier** [comment]
Same story for me.
I use a virtual page. On the settings page there is a link to a help article for 'real page', the link is broken!
I don't understand what the the exact format is of the management page?
It says 'its link must follow your permalink structure.' I'm missing an example here.

I found the KB article here onhithub about making a real page, but I have no succes with it. I think the KB article has errors in it. It says to copy page.php but the screenshot shows index.php?
I'm using Impreza theme and it look these pages are in /framework/templates/...  and these pages already contain some code at the top.
`<?php defined( 'ABSPATH' ) OR die( 'This script cannot be accessed directly.' );

/**
 * The template for displaying pages
 */

$us_layout = US_Layout::instance();
get_header();
us_load_template( 'templates/titlebar' );
?>`
In the KB article, the code shown to insert don't contain 'Header' but the screenshot does?!?
Either way, even then I have no success with coping the page.php and adding the code. I can't select the template on a new page. Is there something missing or maybe it is not working with Impreza theme?

It would be a lot easier if the management page could be built with shortcodes instead of php editing.

**Comment by Reedyseth** [comment]
Hello, I apologize for the outdated information. I will help you to set it
up this week. The plugin is a little bit Rusty, but I will fix this
information so that you can sort it out.

Regards.!!

On Nov 27, 2017 8:52 AM, "KLingier" <notifications@github.com> wrote:

Same story for me.
I use a virtual page. On the settings page there is a link to a help
article for 'real page', the link is broken!
I don't understand what the the exact format is of the management page?
It says 'its link must follow your permalink structure.' I'm missing an
example here.

I found the KB article here onhithub about making a real page, but I have
no succes with it. I think the KB article has errors in it. It says to copy
page.php but the screenshot shows index.php?
I'm using Impreza theme and it look these pages are in
/framework/templates/... and these pages already contain some code at the
top.
`<?php defined( 'ABSPATH' ) OR die( 'This script cannot be accessed
directly.' );

/**

   - The template for displaying pages
   */

$us_layout = US_Layout::instance();
get_header();
us_load_template( 'templates/titlebar' );
?>`
In the KB article, the code shown to insert don't contain 'Header' but the
screenshot does?!?
Either way, even then I have no success with coping the page.php and adding
the code. I can't select the template on a new page. Is there something
missing or maybe it is not working with Impreza theme?

It would be a lot easier if the management page could be built with
shortcodes instead of php editing.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/stcr/subscribe-to-comments-reloaded/issues/381#issuecomment-347225159>,
or mute the thread

**Comment by Reedyseth** [comment]
Hello All,

I have updated the information on the KB, as well as the image where I show how to create the copy. I have reviewed the instructions and they are correct. If you still having issues creating the **Real Management Page** please let me know.
