### ISSUE TITLE
Bug Report: 404 error after clicking subscription confirmation and manage subscriptions

### ISSUE THREAD

**Issue by KrystianErgotopia** [stcr/subscribe-to-comments-reloaded#418]
Neither the confirmation-link nor any other links like manage-subscriptions are working. All result in a 404 error page. I guess its sth. with permalink structure:

I am using this for the posts: https://www.domain.de/blog/%postname%

If you need access to our staging-site for testing purposes pls tell me. I am also willing to pay for fixing this, as we really need this.
a
Thanks!

**Comment by Reedyseth** [comment]
Hi @KrystianErgotopia Thank you for your report.

Usually a 404 on StCR is due to Your Theme that is not able to handle the virtual management page, in which case you have to create a Real management page. The other reason is that the internal database information of StCR and you WordPress database are not matching the same collation, on this case you have to verify both the collation of the tables and the columns. If you have a hard time checking this stuff you can contact me here: http://subscribe-reloaded.com/support-request-system-info/

**Comment by thosch66** [comment]
Hi,

I have sort of the same problem here. But in my case, subcribe-without-comment and confirmation-link work. Only the manager-link is broken.

I use a vanilla theme (Twenty Twelve) which I guess should not be problematic. 

Regards

Thomas

**Comment by Tesacu** [comment]
Do you have iThemes Security plugin actived? If that's your case, try to deactivate the iThemes Security plugin and re-activate it again. That worked for me...
