### ISSUE TITLE
subscribe_reloaded_show() doesn't show anything anymore :)

### ISSUE THREAD

**Issue by AinaBeryl** [stcr/subscribe-to-comments-reloaded#487]
Hi there,
I used to display the subscribe checkbox in comments using the code below in functions.php:

function atelier_comment_form_after_fields(){
	global $wp_subscribe_reloaded;
	if(isset($wp_subscribe_reloaded)){
		echo '<div id="commentsReloaded">';
		$wp_subscribe_reloaded->stcr->subscribe_reloaded_show();
		echo '</div>';
	}
	echo '</div>';
}
add_action('comment_form_after_fields', 'atelier_comment_form_after_fields');

But today (and maybe since several days, I didn't paid attention), I only have an empty <div id="commentsReloaded"></div>.

Does anyone know why?

Thanks!

**Comment by BobaWebDev** [comment]
Hi,

The subscribe_reloaded_show() function now returns instead of echoing. It's changed because the plugin hooks that function to a WordPress filter that expects a return, not an echo. It was causing issues with other plugins.

Use this:

`echo $wp_subscribe_reloaded->stcr->subscribe_reloaded_show();`

**Comment by AinaBeryl** [comment]
Ok, it was just that!
Thanks a lot, it shows again :)
