### ISSUE TITLE
Sidebar in virtual management page

### ISSUE THREAD

**Issue by a2n6ig** [stcr/subscribe-to-comments-reloaded#578]
Is it not possible to display the right sidebar widget on the STCR virtual comment management page?

I'm comfortable with any method. But if there is, please tell me.

**Comment by BobaWebDev** [comment]
Hi @a2n6ig 

StCR uses page.php for that page and only affects the main content area, if a theme adds a sidebar section for regular pages it will show up.

If you use a regular page with the [stcr_management_page] shortcode (instead of the virtual page approach) you can use the theme's options to change the layout.

For example if by default page.php does not have a sidebar it's very likely the theme adds another page template that has a sidebar. Or in some cases it's part of options for the page (in the metaboxes area). Varies from theme to theme, but usually all themes have a way to show both full width page and a page with a sidebar.

**Comment by a2n6ig** [comment]
Okay, thanks :)

**Comment by BobaWebDev** [comment]
You're welcome :)
