### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by MOABlogger** [stcr/subscribe-to-comments-reloaded#586]
Help!

Not sure why some readers are getting this 404 page.  Any help you can provide?
![ScreenHunter_727 May  04 16 11](https://user-images.githubusercontent.com/64807996/81009097-fdb84b80-8e21-11ea-8890-0b8882466241.jpg)

**Comment by MOABlogger** [comment]
Update....I found this in this forum....but

Can you try the following:

Go to WP Admin > StCR > Management Page
Set “Virtual management page” to “No” and save changes
Go to WP admin > Pages > Add New and create a page called “Comment subscriptions”, the permalink should be comment-subscriptions
As the content of that page just add [stcr_management_page]

I still get the same issue.

Do I need to change all my links in the content blocks?

Example:
"Your subscription needs to be confirmed. Manage your subscriptions."

[manager link] = "Manage your subscriptions" 

?

Thanks again,
Mark

**Comment by BobaWebDev** [comment]
Hi @MOABlogger 

I did a test by making a couple comments, you can delete them, they're on the very first post you published.

I received the email and followed the link, it worked fine.

![image](https://user-images.githubusercontent.com/4485586/81050748-d6648b80-8ec0-11ea-92e3-6a9825ce68a4.png)

Can you try again if the issue is resolved, maybe the caching plugin still had it cached as a 404 page so it showed that cached version.

But there's something I noticed, the email looks like:

![image](https://user-images.githubusercontent.com/4485586/81050961-35c29b80-8ec1-11ea-97be-fb282ea9545a.png)

You can see the doubled URLs, first one isn't linked and the second one is.

Do you have HTML emails enabled in **WP admin > StCR > Options**.

![image](https://user-images.githubusercontent.com/4485586/81051091-6c98b180-8ec1-11ea-854d-2739400605b6.png)

If you do, then can you send over a screenshot of the "Notification message" option in **WP admin > StCR > Notifications**

Make sure to switch to **Text** in the top right of the content editor so I see the HTML code.

![image](https://user-images.githubusercontent.com/4485586/81051153-8c2fda00-8ec1-11ea-8008-e18b251f2d28.png)

**Comment by MOABlogger** [comment]
Thanks very much....I really appreciate the testing!!

Seems to have worked and I emailed you back.
fyi - I kept the Author label the same.  

![ScreenHunter_731 May  05 07 45](https://user-images.githubusercontent.com/64807996/81062793-9e4f4f80-8ea4-11ea-85f6-0a62ebbcf324.jpg)


re: Do you have HTML emails enabled in WP admin > StCR > Options?

Mark - I do!

You - If you do, then can you send over a screenshot of the "Notification message" option in WP admin > StCR > Notifications.
Make sure to switch to Text in the top right of the content editor so I see the HTML code.

Mark - I switched it to Text mode and see below the code I have:
 
![ScreenHunter_733 May  05 07 54](https://user-images.githubusercontent.com/64807996/81063417-bc697f80-8ea5-11ea-8d8f-f035967a56b9.jpg)

Thanks for the help in fixing any of that code!

Very much appreciated!

**Comment by MOABlogger** [comment]
Thanks very much for your reply....I really appreciate it!

OK, so I double-checked the 404 and it's gone....so, based on your test,
looks like everything is working great :)

By the way, is this a permanent fix for this solution?




*Go to WP Admin > StCR > Management PageSet “Virtual management page” to
“No” and save changesGo to WP admin > Pages > Add New and create a page
called “Comment subscriptions”, the permalink should be
comment-subscriptionsAs the content of that page just add
[stcr_management_page]  *

*I also updated this wording:*

"Your subscription needs to be confirmed. Manage your subscriptions."

[manager link] = "Manage your subscriptions" was changed in the *Subscribed
label *section:
[image: image.png]



Those were the only fixes I made...

fyi - I kept the* Author label *the same.
[image: image.png]


2. re:

*Do you have HTML emails enabled in WP admin > StCR > Options.*

*Mark - Yes, I do.*

[image: image]
<https://user-images.githubusercontent.com/4485586/81051091-6c98b180-8ec1-11ea-854d-2739400605b6.png>

If you do, then can you send over a screenshot of the "Notification
message" option in WP admin > StCR > Notifications

Make sure to switch to Text in the top right of the content editor so I see
the HTML code.

*Mark - I switched it to Text mode and see below the code I have:*
[image: image.png]

Thanks for the help in fixing any of that code!

Very much appreciated!

Mark

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BobaWebDev** [comment]
Hi @MOABlogger 

Yeah, the solution for the 404 is permanent.

As for the broken HTML issue. In the **Notification Message** option add this https://gist.githubusercontent.com/BobaWebDev/ec9a0255f0361438f36c868cb3f99440/raw/cce598a4cf4ff6b6f5fdbcb00e4062f3ffc33aa0/gistfile1.txt

Add it while in the **Text** mode I mentioned previously.

**Comment by MOABlogger** [comment]
Excellent.

I will give that a try and thanks very much for your work :)

Sincerely,
Mark


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BobaWebDev** [comment]
You're welcome Mark :)

**Comment by MOABlogger** [comment]
Everything seems to be working again, thanks very much!!!

**Comment by BobaWebDev** [comment]
You're welcome
