### ISSUE TITLE
404 site not found after subscription or manage

### ISSUE THREAD

**Issue by crazycat89** [stcr/subscribe-to-comments-reloaded#691]
Hi, I found the following problem. After clicking on "Adjust your notification settings for this post" or "Manage notification settings" only a 404 page appears. The permalink structure is correct. Unfortunately I only discovered it today. However, the double opt-in emails are sent after you have subscribed to a comment.
Link to page: https://bit.ly/3uxzdPQ 
Any ideas?

**Comment by mebishalnapit** [comment]
Could you follow the instructions as stated over here: https://github.com/stcr/subscribe-to-comments-reloaded/issues/681 and see if it helps you out as well?

**Comment by crazycat89** [comment]
Thank you very much. This works fine. Another small problem with the font color, see screencast: https://www.dropbox.com/s/z62dltoq5qxw18b/comments.mov?dl=0

**Comment by mebishalnapit** [comment]
Could you once try the below CSS code in `Appearance -> Customize -> Additional CSS` section and see if that helps:

```
#subscribe-reloaded-action-p > select {
	color: #f00;
}
```

**Comment by crazycat89** [comment]
Unfortunately not … also not with !important.

**Comment by BobaWebDev** [comment]
@crazycat89 

The vertical padding on the select box is larger than the fixed height so all you see is the padding (because the box-sizing is set to border-box), no room for actual text.

You need to set the height to auto (or decrease the padding).

```#subscribe-reloaded-action-p > select {
	height: auto
}```

Keep in mind this not an issue coming from the plugin, so you'll have the same problem on all select boxes on the site. The code above fixes it only for the select box in the theme.

**Comment by crazycat89** [comment]
Thanks. Now it works. But that was just on this site. On all other sites, select boxes works fine … 🤷‍♀️
