### ISSUE TITLE
Post SMTP email error

### ISSUE THREAD

**Issue by mygutfeeling** [stcr/subscribe-to-comments-reloaded#743]
Hi! I get this message everytime I accept or reply to a comment:

You getting this message because an error detected while delivered your email.
For the domain: https://www....
The log to paste when you open a support issue:
The given data was invalid. The from.email must be verified.

I think is related to the plugin. Is it possible? and how can I solve it?

Thx!

**Comment by BobaWebDev** [comment]
Hi @mygutfeeling 

"The from email must be verified". 

I assume that you are using an email address under the same domain name as the site, correct?

Some email service providers only let existing email addresses to be used as the sender, which might be the issue here. Make sure that the address you have set as `Sender email address` in `WP admin > StCR > Notifications` is a real existing email address.

Also, do other emails work fine? For example try requesting a password reset (don't reset of course, just check if you're receiving the email for the reset).

**Comment by mygutfeeling** [comment]
HI Slobodan,

Thank you :) I had an old gmail and it worked for years but changed as you
suggested and issue seems to be resolved!

thx!

-
Joana
<http://instagram.com/my_gut_feeling>



Slobodan Kustrimovic ***@***.***> escreveu no dia terça,
4/10/2022 à(s) 08:53:

**Comment by BobaWebDev** [comment]
Hi @mygutfeeling 

You're welcome, happy to hear it's working now :)
