### ISSUE TITLE
Bug Report: <short description>

### ISSUE THREAD

**Issue by yanivinio** [stcr/subscribe-to-comments-reloaded#747]
Hello
in "Subscribe to Comments Reloaded" wordpress addon
i recive 4 emails for evey subscriber
it started since yesterday

thank you

**Comment by BobaWebDev** [comment]
Hi @yanivinio 

Have you installed any additional (or update existing) plugins in the period since it worked fine and the issue started?

Which emails are you receiving? The notifications of new comments?

Can you send over the System Log (WP admin > StCR > StCR System, then click the "Download" button for "Download System Info File") via the contact form on https://subscribe-reloaded.com/contact/

**Comment by yanivinio** [comment]
i updated Wordpress version and since i got 5 e-mails for every subscriber 
i sent the file....

**Comment by BobaWebDev** [comment]
Hi @yanivinio 

Can you let me know about the questions?

> Have you installed any additional (or update existing) plugins in the period since it worked fine and the issue started?

> Which emails are you receiving? The notifications of new comments?

**Comment by yanivinio** [comment]
Have you installed any additional (or update existing) plugins in the period since it worked fine and the issue started?
Yes, i updated Wordpress version

Which emails are you receiving? The notifications of new comments?
every time someone subscribe to comment - i get 5 e-mails instead of 1

you can see screenshot here - https://ibb.co/KWPmMtH

thank you

**Comment by BobaWebDev** [comment]
Hi @yanivinio 

Happy to hear that, but no changes were done to the plugin. 

If the issue shows up again let us know.
