### ISSUE TITLE
Notification email link displays Page Not Found error

### ISSUE THREAD

**Issue by sdarnowsky** [stcr/subscribe-to-comments-reloaded#773]
Our website (cincinnatifriends.org) previously had Enable double-check set to Yes in the Options page for StCR. A user added a comment to a blog post and selected the check box to receive notifications every time a new comment was added. That user received the double-check email. However, when the user clicked the supplied link to confirm the request, the link took the user to a Page Not Found error.

Is there something we need to configure on our end to ensure that this functionality works? This seems like a bug. For the time being, I have set the Enable double-check option to No so that other users won't receive a link to a bogus page.

![image](https://github.com/stcr/subscribe-to-comments-reloaded/assets/134307914/226eb682-7ef5-4757-b425-1195b26f208c)

**Comment by sdarnowsky** [comment]
I also left a comment myself on the same blog post, and noticed that the links to "Manage your subscriptions" and "Manage the subscriptions of this post" also produce a Page Not Found Error. I may have to disable this plug-in entirely if it doesn't function without errors.

**Comment by BobaWebDev** [comment]
Hi @sdarnowsky 

Can you try creating a regular page instead of the virtual page that StCR has.

- Go to WP Admin > StCR > Management Page
- Set "Virtual management page" to "No" and save changes
- Go to WP admin > Pages > Add New and create a page called "Comment subscriptions", the permalink should be `comment-subscriptions`
- For the content of the page add `[stcr_management_page]`

**Comment by sdarnowsky** [comment]
That did the trick for fixing the subscription management issue! Thanks!!

**Comment by BobaWebDev** [comment]
You're welcome.
