### ISSUE TITLE
Receiving multiple emails on new subscriptions

### ISSUE THREAD

**Issue by obs0lete** [stcr/subscribe-to-comments-reloaded#793]
Hello,

Whenever someone subscribes to a post, I receive about 6 emails letting me now about the new subscription.
The emails are all the same:

"New subscription to..."

I see there was a similar issue https://github.com/stcr/subscribe-to-comments-reloaded/issues/777 but this went nowhere.
The URL for the site is https://thishealthykitchen.com/

Thanks in advance.

**Comment by BobaWebDev** [comment]
Hi @obs0lete 

Do you have "Enable double check" (subscribers have to confirm their subscription by clicking a link they get on email) enabled?

I see on the subscription management page that the form from STCR is shown in a few places https://thishealthykitchen.com/comment-subscriptions/

That's also the page where the confirmation for the subscriptions goes to. 

Since it shows in a few different places on the same page the system does the same thing multiple times.

Can you try the following:

- Go to WP Admin > StCR > Management Page
- Set “Virtual management page” to “No” and save changes
- Go to WP admin > Pages > Add New and create a page called “Comment subscriptions”, the permalink should be `comment-subscriptions`
- For the content of the page add `[stcr_management_page]`

**Comment by obs0lete** [comment]
> Hi @obs0lete
> 
> Do you have "Enable double check" (subscribers have to confirm their subscription by clicking a link they get on email) enabled?
> 
> I see on the subscription management page that the form from STCR is shown in a few places https://thishealthykitchen.com/comment-subscriptions/
> 
> That's also the page where the confirmation for the subscriptions goes to.
> 
> Since it shows in a few different places on the same page the system does the same thing multiple times.
> 
> Can you try the following:
> 
>     * Go to WP Admin > StCR > Management Page
> 
>     * Set “Virtual management page” to “No” and save changes
> 
>     * Go to WP admin > Pages > Add New and create a page called “Comment subscriptions”, the permalink should be `comment-subscriptions`
> 
>     * For the content of the page add `[stcr_management_page]`

Finally got around to looking at this. That seems to have fixed it for me. Thank you!
